# Generated by Django 5.1.4 on 2025-04-26 09:45

import django.db.models.deletion
import petmemorial.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetMemorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=petmemorial.models.pet_memorial_profile_photo_path)),
                ('pet_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('year_of_birth', models.IntegerField()),
                ('year_of_death', models.IntegerField()),
                ('tribute_quote', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('ferret', 'Ferret'), ('bird', 'Bird'), ('parrot', 'Parrot'), ('turtle', 'Turtle'), ('lizard', 'Lizard'), ('snake', 'Snake'), ('fish', 'Fish'), ('horse', 'Horse'), ('goat', 'Goat'), ('pig', 'Pig'), ('chicken', 'Chicken'), ('duck', 'Duck'), ('frog', 'Frog'), ('hedgehog', 'Hedgehog'), ('other', 'Other')], max_length=100)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('dominant_traits', models.CharField(blank=True, max_length=100, null=True)),
                ('about_pet', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('owner_display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet_memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='petmemorial.petmemorial')),
            ],
        ),
        migrations.CreateModel(
            name='PetMemorialGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=petmemorial.models.gallery_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('pet_memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='petmemorial.petmemorial')),
            ],
        ),
    ]
