# Generated by Django 5.1.4 on 2025-04-26 15:57

import django.db.models.deletion
import petmemorial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmemorial',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MemorialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=petmemorial.models.gallery_image_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='petmemorial.petmemorial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='PetMemorialGalleryImage',
        ),
    ]
