# Generated by Django 5.1.4 on 2025-05-04 09:03

import petmemorial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmemorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmemorial',
            name='photo',
            field=models.ImageField(default='users/default/petmemorial/default.jpg', upload_to=petmemorial.models.pet_memorial_profile_photo_path),
            preserve_default=False,
        ),
    ]
